tinytex::tlmgr_install(c("epstopdf-pkg"))
tinytex::tlmgr_install(c("collectbox"))
tinytex::tlmgr_install(c("adjustbox"))
tinytex::tlmgr_install(c("pdftexcmds"))
tinytex::tlmgr_install(c("psnfss"))
tinytex::tlmgr_install(c("bbm-macros"))
tinytex::tlmgr_install(c("doublestroke"))
tinytex::tlmgr_install(c("multirow"))
tinytex::tlmgr_install(c("bbold"))
tinytex::tlmgr_install(c("setspace", "lineno", "hyperref", "makecell", "times"))
tinytex::tlmgr_install(c("courier"))
