# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_row_cpp <- function(x, n, ploidy, min_maf) {
    .Call('pcadapt_get_row_cpp', PACKAGE = 'pcadapt', x, n, ploidy, min_maf)
}

#' Compute graph matrix with the heat kernel function.
#' 
#' @export
lrfunc_cpp <- function(scores, Geno, K, nIND, nSNP, ploidy, min_maf) {
    .Call('pcadapt_lrfunc_cpp', PACKAGE = 'pcadapt', scores, Geno, K, nIND, nSNP, ploidy, min_maf)
}

