# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

af <- function(obj, lookup_scale, lookup_byte) {
    .Call('_pcadapt_af', PACKAGE = 'pcadapt', obj, lookup_scale, lookup_byte)
}

bedXPtr <- function(path, n, p) {
    .Call('_pcadapt_bedXPtr', PACKAGE = 'pcadapt', path, n, p)
}

get_sumX <- function(obj, lookup_scale, lookup_byte) {
    .Call('_pcadapt_get_sumX', PACKAGE = 'pcadapt', obj, lookup_scale, lookup_byte)
}

get_denoX <- function(obj, lookup_scale, lookup_byte, m) {
    .Call('_pcadapt_get_denoX', PACKAGE = 'pcadapt', obj, lookup_scale, lookup_byte, m)
}

clumping <- function(obj, lookup, lookup_byte, ord, remain, sumX, denoX, size, thr) {
    .Call('_pcadapt_clumping', PACKAGE = 'pcadapt', obj, lookup, lookup_byte, ord, remain, sumX, denoX, size, thr)
}

multLinReg <- function(obj, lookup_scale, lookup_byte, u, d, v) {
    .Call('_pcadapt_multLinReg', PACKAGE = 'pcadapt', obj, lookup_scale, lookup_byte, u, d, v)
}

nb_nona <- function(obj, lookup_scale, lookup_byte) {
    .Call('_pcadapt_nb_nona', PACKAGE = 'pcadapt', obj, lookup_scale, lookup_byte)
}

#' Robust estimates for location and scatter
#'
#' \code{covRob_cpp} implements the Orthogonalized Gnanadesikan-Kettenring estimator
#' of Maronna and Zamar.
#'
#' @param x a numeric matrix.
#' 
#' @examples
#' ## see also ?pcadapt for examples
#'
#' @export
#'
covRob_cpp <- function(x) {
    .Call('_pcadapt_covRob_cpp', PACKAGE = 'pcadapt', x)
}

pMatVec4 <- function(obj, x, lookup_scale, lookup_byte, pass) {
    .Call('_pcadapt_pMatVec4', PACKAGE = 'pcadapt', obj, x, lookup_scale, lookup_byte, pass)
}

cpMatVec4 <- function(obj, x, lookup_scale, lookup_byte, pass) {
    .Call('_pcadapt_cpMatVec4', PACKAGE = 'pcadapt', obj, x, lookup_scale, lookup_byte, pass)
}

#' File size
#' 
#' \code{get_size_cpp} returns the number of genetic markers and the number of 
#' individuals present in the data.
#' 
#' @param filename a character string specifying the name of the file to be 
#' processed with \code{pcadapt}.
#' 
#' @return The returned value is a numeric vector of length 2.
#' 
#' @export
#' 
get_size_cpp <- function(filename) {
    .Call('_pcadapt_get_size_cpp', PACKAGE = 'pcadapt', filename)
}

#' Number of individuals in a specific population
#' 
#' \code{get_nb_ind} returns the number of individuals in a specific population.
#' 
#' @param pop a string vector.
#' @param name a character vector.
#' 
#' @return The returned value is an integer.
#' 
#' @export
#' 
get_nb_ind <- function(pop, name) {
    .Call('_pcadapt_get_nb_ind', PACKAGE = 'pcadapt', pop, name)
}

#' Minor allele frequencies
#' 
#' \code{cmpt_minor_af} computes the minor allele frequencies.
#' 
#' @param xmatrix a genotype matrix.
#' @param ploidy an integer specifying the ploidy of the individuals.
#' 
#' @return The returned value is a numeric matrix.
#' 
#' @export
#' 
cmpt_minor_af <- function(xmatrix, ploidy) {
    .Call('_pcadapt_cmpt_minor_af', PACKAGE = 'pcadapt', xmatrix, ploidy)
}

#' Scale genotype matrices
#' 
#' \code{scale_geno} scales the genotype matrix.
#' 
#' @param xmatrix a genotype matrix.
#' @param ploidy an integer specifying the ploidy of the individuals.
#' @param maf a vector of minor allele frequencies.
#' @param keep_or_not a vector of integers.
#' 
#' @return The returned value is a numeric matrix.
#' 
#' @export
#' 
scale_geno <- function(xmatrix, ploidy, maf, keep_or_not) {
    .Call('_pcadapt_scale_geno', PACKAGE = 'pcadapt', xmatrix, ploidy, maf, keep_or_not)
}

#' Compute the loadings
#' 
#' \code{cmpt_loadings} returns the loadings.
#' 
#' @param filename a character string specifying the name of the file to be 
#' processed with \code{pcadapt}.
#' @param xmatrix a genotype matrix.
#' @param scores a matrix containing the scores.
#' @param nIND an integer specifying the number of individuals present in the 
#' data.
#' @param nSNP an integer specifying the number of genetic markers present in 
#' the data.
#' @param K an integer specifying the number of principal components to retain.
#' @param ploidy an integer specifying the ploidy of the individuals.
#' @param min_maf a value between \code{0} and \code{0.45} specifying the 
#' threshold of minor allele frequencies above which p-values are computed.
#' @param sigma a numeric vector.
#' @param type an integer specifying the input type.
#' 
#' @return The returned value is a matrix containing the loadings.
#' 
#' @export
#' 
cmpt_loadings <- function(filename, xmatrix, scores, nIND, nSNP, K, ploidy, min_maf, sigma, type) {
    .Call('_pcadapt_cmpt_loadings', PACKAGE = 'pcadapt', filename, xmatrix, scores, nIND, nSNP, K, ploidy, min_maf, sigma, type)
}

#' Linear regression
#' 
#' \code{lrfunc_cpp} performs the multiple linear regression of the genotype 
#' matrix on the scores.
#' 
#' @param filename a character string specifying the name of the file to be 
#' processed with \code{pcadapt}.
#' @param xmatrix a genotype matrix.
#' @param scores a matrix containing the scores.
#' @param nIND an integer specifying the number of individuals present in the 
#' data.
#' @param nSNP an integer specifying the number of genetic markers present in 
#' the data.
#' @param K an integer specifying the number of principal components to retain.
#' @param ploidy an integer specifying the ploidy of the individuals.
#' @param min_maf a value between \code{0} and \code{0.45} specifying the 
#' threshold of minor allele frequencies above which p-values are computed.
#' @param sigma a numeric vector.
#' @param type an integer specifying the input type.
#' 
#' @return The returned value is a Rcpp::List containing the multiple linear 
#' regression z-scores, the minor allele frequencies and the number of missing 
#' values for each genetic marker.
#' 
#' @export
#' 
lrfunc_cpp <- function(filename, xmatrix, scores, nIND, nSNP, K, ploidy, min_maf, sigma, type) {
    .Call('_pcadapt_lrfunc_cpp', PACKAGE = 'pcadapt', filename, xmatrix, scores, nIND, nSNP, K, ploidy, min_maf, sigma, type)
}

#' Sample genotype matrix from pooled samples
#' 
#' \code{sample_geno_file} sample genotypes based on observed allelic frequencies.
#' 
#' @param input a character string specifying the name of the file containing the allele frequencies.
#' @param output a character string specifying the name of the output file.
#' @param ploidy an integer specifying the ploidy of the sampled individuals.
#' @param sample_size a vector specifying the number of individuals to be sampled for each pool.
#' 
#' @return The returned value is a numeric vector of length 2.
#' 
#' @export
#' 
sample_geno_file <- function(input, output, ploidy, sample_size) {
    .Call('_pcadapt_sample_geno_file', PACKAGE = 'pcadapt', input, output, ploidy, sample_size)
}

